bin/smarthome.py
examples/smarthome.service
lib/daemon.py
var/run/.gitignore

create a pidfile (var/run/smarthome.py) for systemd on startup

create pidfile on start

---

plugins/hue/README.md
plugins/hue/__init__.py
plugins/hue/fetch_url_v2.py

Hallo,
ich hatte das Hue Plugin schon neu geschrieben, weil das alte nicht supported war und auch Funktionen fehlen. Anbei der aktuelle Stand. Ich hatte schon versucht den PR bei Marcus zu stellen, bislang gescheitert, vielleicht klappt es ja im neuen Zweig.
Michel

v 1.71 des neu geschrieben Plugins

---

plugins/systemair/README.md
plugins/systemair/__init__.py
plugins/systemair/systemair.conf

Hi,
please commit the new systemair modbus plugin.
Thanks,
Stefan

systemair modbus plugin v0.1

---

bin/smarthome.py

Fixed object refcount for broken Python Installations (Debian/Ubuntu).

---

plugins/influxdata/README.md
plugins/influxdata/__init__.py

InfluxData (InfluxDB) plugin which sends entries over UDP.

InfluxDB plugin

---

plugins/yamaha/README.md
plugins/yamaha/__init__.py

Yamaha AV plugin

---

plugins/plex/README.md
plugins/plex/__init__.py

Plex notification plugin

---

plugins/gpio/README.md
plugins/gpio/__init__.py

Plugin to read and write GPIO pins from Raspi

GPIO plugin

---

plugins/logo/README.md
plugins/logo/__init__.py

Anpassungen für SmartHomeNG Release 1.2; Erben der Klasse SmartPlugin; Testen von Multiinstance

Anpassungen für SmartHomeNG Release 1.2; Erben der Klasse SmartPlugin; Testen von Multiinstance

---

etc/plugin.conf.default
lib/tools.py
lib/utils.py
plugins/cli/README.md
plugins/cli/__init__.py
tests/test_utils.py

I did some redesign on the CLI Plugin:
- Change into SmartPlugin
- Require passwort to logon
- Prepare for other plugins to add own commands (similar to my sh.py pull request 181)
For the password I added a function "create_hash" to the general SmartHomeNG Tools class. It should be possible to use this function for the hashed password in the backend plugin, too (#101)

Redesign CLI Plugin

---

plugins/sml/__init__.py

Make use of SmartPlugin and update plugin to support multi-instances.

Make SML plugin multi-instanceable

---

plugins/dashbutton/README.md
plugins/dashbutton/__init__.py

Now it's possible to pass a list to 'dashbutton_value'. Additionally i've added a 'dashbutton_reset' attribute (see README.md for more informations).

New functionality added for Dashbutton plugin

---

plugins/sonos/README.md
plugins/sonos/__init__.py

switched versioning equal to Sonos Broker version
updated documentation

minor updates, changed versioning

---

plugins/drexelundweiss/__init__.py
plugins/drexelundweiss/x2_plus.txt

.. Smart Plugin, error handling, connection retries.

Updated Drexel und Weiss Plugin

---

plugins/sonos/README.md
plugins/sonos/__init__.py
plugins/sonos/examples/sonos.conf

some updates for new Sonos Broker version

changed to v0.9

---

plugins/squeezebox/README.md
plugins/squeezebox/__init__.py

* The plugin is now a Smart Plugin. You can change the logging level in logging.yaml
* When the end of a playlist is reached the plugin now changes the mode correctly to "stop" 
* When playing a radio station the play mode is now correctly set to "play"
* When starting playing by adding and playing a playlist the play mode is now correctly set to "play"
* The player_id in your conf file is now searched not only in the parent item but also 2 levels further up

squeezebox Plugin: smart plugin, fixed some issues with playlist mode updates

---

lib/item.py

hello,
imported the math module to support eval expressions like the following:
[[[[stellantrieb]]]]
type = num
eval = math.floor( value / 255 * 100 )
knx_dpt = 5
knx_listen = 3/2/5
knx_init = 3/2/5

imported math-module to support eval expressions

---

plugins/database/__init__.py

This correct the wrong licence header.

Fix licence header: remove cstrassburg, add ohinckel

---

lib/tools.py

returns relative humidity if the absolute humidity and the temperature are given

abs2rel(self,t,ah) added

---

modules/http/__init__.py

fixes #281
removed spaces in empty line and at end of line (autopep8)

Update http module for offline mode

---

lib/network.py

Http class accepts timeout parameter

lib/network: include timeout

---

modules/mqtt/__init__.py

Fix for issue described in #355

Fix hardcoded directory levels (smarthomeNG/smarthome#355)

---

lib/item/item.py
modules/admin/api_services.py

relative items were not extracted correctly when using item properties instead of the old way

fix relative item evaluation with property

---

lib/logutils.py

when filters are active and logging message is just a boolean value

logging: fix error with filtering messages

---

doc/user/source/installation/komplettanleitung/04_smartvisu.rst

Finally, I hope now it is only one click for you to merge it...
Thanks for your patience.

Adjusted smartvisu URL to lowercase.

---

dev/sample_module/__init__.py
lib/aioudp.py
lib/network.py
lib/utils.py
modules/admin/__init__.py
modules/mqtt/__init__.py
modules/websocket/__init__.py
tests/mock/core.py

- lib.network was partly rewritten and enhanced
- UDP server added
- streamlined and documented features and API
- removed some tools which were duplicates with lib.utils (moved code updates to lib.utils too)
- further details: see commit history

lib.network: overhaul to be mostly feature-compatible with lib.connection

---

lib/connection.py

lib.connection: show deprecation warning

---

lib/item/item.py

where last character of expression part got truncated and therefore eval expression might get invalid

get relative item path: fix issue

---

lib/network.py

lib.network: fix for logging

---

doc/user/source/konfiguration/logging_best_practices.rst
doc/user/source/referenz/logging/logging_filter.rst
doc/user/source/visualisierung/reverse_proxy.rst

make clear the entries have to be regular expressions

docu: update logging filters reference

---

lib/model/smartplugin.py

rename self._item_dict to self._plg_item_dict to prevent naming collisions with existing plugins
rename _plg_item_dict sub-key "has_trigger_method" to "is_updating"
corrected/added some commenting

smartplugin: fixes to dict and function naming

---

dev/sample_mqttplugin/plugin.yaml
dev/sample_mqttplugin/webif/__init__.py
dev/sample_mqttplugin/webif/templates/index.html
dev/sample_plugin/plugin.yaml
dev/sample_plugin/webif/__init__.py
dev/sample_plugin/webif/templates/index.html
doc/user/source/entwicklung/plugins/webinterface_automatic_update.rst
doc/user/source/entwicklung/plugins/webinterface_filling_webinterface.rst
doc/user/source/entwicklung/plugins/webinterface_plugin_interaction.rst
modules/http/README.md
modules/http/__init__.py
modules/http/module.yaml
modules/http/webif/gstatic/css/smarthomeng.css
modules/http/webif/gstatic/datatables/datatables.defaults.js
modules/http/webif/gstatic/js/smarthomeng.js
modules/http/webif/gstatic/js/smarthomeng_pageupdate.js
modules/http/webif/gtemplates/base_plugin.html

Currently I am using JS to make the top header as responsive as possible.
Additionally, some updates to datatables are implemented. It is now necessary to add an empty first cell in each row.

Http Module: make header responsive

---

modules/http/webif/gstatic/css/smarthomeng.css
modules/http/webif/gstatic/datatables/dataTables.pageResize.min.js
modules/http/webif/gstatic/datatables/datatables.defaults.js

(fix responsive issues on tab load/change, include <div> above datatable in resize calculation, changed table-layout to auto instead of fixed)

http module: improve datatable implementation 

---

dev/sample_mqttplugin/webif/templates/index.html
dev/sample_plugin/webif/templates/index.html
doc/user/source/entwicklung/plugins/webinterface_filling_webinterface.rst
modules/http/webif/gstatic/datatables/dataTables.pageResize.min.js
modules/http/webif/gstatic/datatables/datatables.defaults.js
modules/http/webif/gstatic/js/smarthomeng_pageupdate.js
modules/http/webif/gtemplates/base_plugin.html

fix resize calculation.. consider all divs with class mb-2 in current tab for resize; instant update table refresh if checkbox for autoupdate is activated

http module: improve resizing

---

tools/backup_restore.py

proposed fix for CVE-2007-4559 in tarfile.py, adapted from https://stackoverflow.com/questions/10060069/safely-extract-zip-or-tar-using-python/10077309#10077309

backup_restore.py: proposed fix for tarfile extractall

---

doc/user/source/dummy_for_readmes.rst
doc/user/source/lib/connection.rst
doc/user/source/referenz/smarthomeng/ablauf_startup #2.rst
doc/user/source/referenz/smarthomeng/ablauf_startup.rst
lib/connection.py
lib/smarthome.py
modules/admin/webif/static/assets/testdata/api/loggers/default.json

Reverts smarthomeNG/smarthome#537
This removal of lib.connection should nit be included in a bugfix release.

Revert "remove lib.connection"

---

lib/network.py

Reverts smarthomeNG/smarthome#543
Doesnt seem to work.. knx_init e.g. not working (always)

Revert "minor fixes to lib.network"

---

modules/http/webif/gstatic/datatables/datatables.defaults.js

http module: remove window.resize on click on responsive "+" sign 

---

lib/model/sdp/connection.py

sdp: fix result error handling for serial connections

---

lib/shpypi.py

Es wurde bisher eine Liste von dicts zurückgeliefert, wenn es mehr als einen Eintrag gab. Das führte dann später zu Fehlern, weil als Ergbnis eine Liste und keine Dictionaries erwartet wurden. Das sollte jetzt behoben sein. Die Werte werden kosolidiert.

lib.shpypi: Update _split_requirement

---

lib/item/item.py

lib.item: cast cached value on initialization

---

lib/model/sdp/commands.py
lib/model/smartdeviceplugin.py

minor enhancements for integrating normal and standalone mode

sdp: improvements

---

doc/user/source/referenz/logging/logging_handler.rst
lib/log.py

when using DateTimeRotatingFileHandler

lib.log: allow weekly, monthly and yearly rotation 

---

tools/cpuusage.py

cpuusage: wait for shng pid

---

lib/model/smartplugin.py

smartplugin: add method to get/remove all schedulers for smartplugin 

---

modules/websocket/smartvisu.py

module.websocket: fix smartvisu item monitoring

---

.gitignore
doc/user/source/referenz/items/standard_attribute/autotimer.rst
doc/user/source/referenz/items/standard_attribute/cycle.rst
lib/item/helpers.py
lib/item/item.py
lib/scheduler.py

additional minor fixes and format edits

extend cycle and autotimer to accept eval expressions
