lib/tools.py
added optional flag to disable warning logs when devices are not permanently online.
=> fetch_url, optionally disable warning logs

lib/item.py, plugins/cli/README.md, plugins/cli/__init__.py
(copied from https://github.com/mknx/smarthome/pull/138)
This will add a new CLI command named `dump` which display additional information for a given item. It could really be handy when trying to debug something (e.g. logics) to know the items current state and all information related to an item (e.g. previous value, last change, method and logic triggers,  ...).
Example output:
```
> dump env.core.memory
Item env.core.memory {
type = num
value = 14188544
age = 56.113745
last_change = 2014-11-18 21:34:38.136741+01:00
changed by = Logic:None
previous value = 0
previous age = 14.555422
previous_change = 2014-11-18 21:34:23.581319+01:00
config = {
sqlite = init
}
}
>  dump light.l1
Item light.l1 {
type = bool
value = False
age = 155.85737
last_change = 2015-11-29 21:44:46.320419+01:00 …
```
=> New CLI command: dump

lib/scheduler.py
(copied from https://github.com/mknx/smarthome/pull/61)
I started to refactor the `scheduler._range()` function a little bit and implemented support for `x/y` and `x-y` as requested in issue #59. The function was changed to resolve the `crontab` elements from complex to simple elements.
The following complex elements are supported now in `crontab` setting:
* list, e.g. `1,2,3,4,8-10`
* intervals, e.g. `*/2`
* ranges, e.g. `0-8`
Since the resolving is implemented in a recusive way, it's also possible to combine all of them. E.g. you can use `1,2,3,4,8-10` or `1-4,5-23/2` or something similar. The first one will include the hours between 1-4 and 8-10, the second one will include the hours between 1-4 and each even hour between 5 and 23.
=> Issue 59: Support crontab ranges 'x-y' and 'x/y'

lib/config.py
(copied from https://github.com/mknx/smarthome/pull/167)
Some configuration options may get long values assigned (e.g. the eval or trigger settings). These long values are not very comfortable to be edited in an editor since the complete line is not shown.
To ease editing of these long values this patch introduces a continuation character (`\`) which can be used at the end of the line to indicate the following line should be appended.
```
[some_logic_configuration]
filename = logic-script.py
watch_item = \
path.to.item|\
path.to.item.child|\
path.to.otheritem|\
path.to.otheritem.child
```
=> Line continuation in config files

plugins/datalog/__init__.py
This will fix the handling of the file and log patterns in case only one item is explicitely configured. The previous version was assuming that both parameters are specified as list (or dict). But having only one configured it is treated as single string value.
Fixes #86.
=> Fix handling of single file and log pattern

plugins/backend/__init__.py, plugins/backend/locale/de.json, plugins/backend/locale/en.json, plugins/backend/locale/fr.json
Productive Systems may not have internet access. (At least mine doesn't) In this case checking for
current versions of python packages takes a very long time. In my case every
checked package fails after two minutes. So page "System Info" seems to be inaccessible because it has tremendous load times.
This change checks accessibility of PyPI by trying to enable a socket connection
with a 5 second timeout. If no connection can be made within this time, reading
current versions of python packages will not happen. Instead a message is being shown that PyPI is inaccessible.
Someone may have a look on the french translation of the message. I do not speak french, so I had Google translate the message ...
=> Backend Plugin: Consider PyPI may be inaccessible

plugins/backend/README.md, plugins/backend/__init__.py, plugins/backend/locale/de.json, plugins/backend/locale/en.json, plugins/backend/locale/fr.json
As discussed in #99:
The timeout for checking if a connection to PyPI can be established is now configurable in the plugin configuration via parameter "pypi_timeout".
Default value is 5 seconds. If the value is set to 0, the PyPI check will be disabled.
Documentation has been adapted accordingly
=> Backend Plugin: Timeout for PyPI access check configurable

bin/smarthome.py
(copied from https://github.com/mknx/smarthome/pull/175)
The `sh.match_items()` method is already able to mach items by a given attribute names and return a list of items having the given attribute.
Usually you're using this to identify item having some characteristics. But sometimes you have the same attribute with different values configured and want to handle them differently, for example when connecting them to some logics using `watch_item` setting.
You can now do
* `sh.match_items("some.items.*:attr")` which returns items with the attribute `attr` (already working)
* `sh.match_items("some.items.*:attr[value]")` which returns items with the attribute `attr` set to value `value` (new)
The value checking supports
* simple types (e.g. str, int, ...) by checking equality (e.g. `attr = …
=> Make it possible to match on item attribute and it's value

plugins/systemair/__init__.py
Hi,
I'm using systemair plugin with VTR200/B and it works well, but I think that using serial port without any protection isn't very elegant, even with resends handled. To solve this, I added threading.Lock() to this plugin. In my case this change eliminates resend warnings and "Port is already open." errors.
Since this is my first contribution, I hope for feedback, especially from @pfischi :)
4d4mu
=> systemair: use modbus serial port with threading.Lock()

plugins/systemair/README.md, plugins/systemair/__init__.py, plugins/systemair/systemair.conf, requirements/plugins.systemair.txt
Hi,
My vent told me, that last night temperature was over +6500*C!
There's a bug in systemair plugin - all values are parsed as unsigned. Minimalmodbus has optional argument for signed/unsigned, but only for reading one reg, not group. Since group read is faster, i decided to convert temperatures with ctypes. According to systemair modbus manual, only heater regs contain temperatures and rest of heater regs doesn't exceed value 32767, so I applied fix to all heater regs (for simplicity).
=> systemair: fix bug with unsigned temperatures

plugins/drexelundweiss/DrexelWeiss.conf, plugins/drexelundweiss/README.md, plugins/drexelundweiss/__init__.py, plugins/drexelundweiss/x2_plus.txt
Changed some additional code to make plugin smart (really this time) and added some more help and an example conf.
Complete changelog compared to original plugin from Bernator:
* Ignore wrong device info and use backup device id (set correct number for your DuW device from list below)
* Retry reading lines to prevent wrong data (set value in conf file)
* Catch division by zero errors
* expanded config file for x2 plus. See http://filter.drexel-weiss.at/HP/Upload/Dateien/900.6667_00_TI_Modbus_Parameter_V4.01_DE.pdf for further parameters
* Plugin is smart so you can use seperate logging level in logging.yaml
* Fixed some code
* Added example config file in plugins folder
=> Drexel und Weiss Plugin updated, made smart, added examples

plugins/sqlite/__init__.py, plugins/sqlite_visu2_8/__init__.py
Due to a missing lock in the `dump()` and `maintain()` method it could happen that the internal item buffer changes while running the dump or maintenance and stops with error:
`RuntimeError: dictionary changed size during iteration`.
This fix will add the lock and avoid this error - still untested but should be working since it is a minimal patch. Please test!
=> Fix issue #82 - lock buffer while running dump/maintain

lib/model/smartplugin.py, requirements/test.txt, tests/mock/core.py, tests/resources/plugin.conf, tests/resources/plugin.yaml, tests/test_plugin.py
This PR contains:
* start implementing core mock objects for reuse in other tests
* decrease code-duplications in SmartPlugin attribute name calculation
* refactor tests for plugin and create small functions to actually tests units of plugin handling
(previously included in #127)
=> Common mock objecsts for tests

bin/smarthome.py
Allow to configure additional module pathes in SmartHome configuration by using the `module_pathes` setting. It can be used to specify a single path or a list of pathes which will be added to the Python module search path.
This could be useful if users want to use other 3rd party modules which are not part of the SmartHome project.
=> Make additional module pathes configurable

lib/config.py, tests/resources/config_keyword.conf, tests/resources/config_keyword.yaml, tests/test_config.py
Using keywords in configuration can lead to problem. Especially
when the configuration is referenced in some Python expressions
like eval attribute in items.conf.
Fixes #180 Items with same root item spread over multiple config files.
=> Ignore keywords in configuration files

modules/http/__init__.py
Just switched to newest develop and find out this issue with http module: 
`2017-09-18 19:12:14 ERROR    module       Main         Module http exception: [Errno 1]  Unknown host -- module.py:__init__:81
Traceback (most recent call last):
File "/home/smarthome/smarthome/lib/module.py", line 79, in __init__
self._load_module(module, classname, classpath, args)
File "/home/smarthome/smarthome/lib/module.py", line 224, in _load_module
exec("self.loadedmodule.__init__(self._sh{0}{1})".format("," if len(arglist) else "", argstring))
File "<string>", line 1, in <module>
File "/home/smarthome/smarthome/modules/http/__init__.py", line 86, in __init__
self.logger.info("Module 'http': ip address = {}, hostname = '{}'".format(self.get_local_ip_address(), self.get_local_hostname()))
File …
=> module http: fix hostname resolving

.travis.sh, .travis.yml, doc/build_doc.sh
This is an update for the Travis-CI build:
* updated `tox.ini` and `.travis.yml`
* introduced new `.travis.sh` script which is used to run the suite
It will enable execution of tests when committing to the `core` repository. An example run can be reviewed [here](https://travis-ci.org/ohinckel/smarthomeNG-core/jobs/328408455). The [documentation](https://github.com/smarthomeNG/smarthome/wiki/Tests) will also be updated after merge.
The execute will be unified with this PR so that the `plugins` and `core` repositories uses the same script and configuration and run the suite as follows:
* commits to `master` will run the tests using both repositories' `master` branch
* commits to `develop` will run the tests using both repositories' `develop` branch
(see also …
=> Update Travis-CI build

lib/daemon.py
As suggested in the discussion for PR #252, this patch uses file locking for the pidfile to improve check_sh_is_running().
A lock is set by the daemon process and then check_sh_is_running tests if it can acquire the lock in the second process. If not, there is no other daemon process running, even if the pidfile exists.
Issue with this code:
The daemon thread needs to wait for the pidfile to exist before the lock can be placed.
We could also write the pidfile from the daemon process itself or use a separate lockfile instead.
=> Improve process-running detection

lib/logutils.py
Da ich aus dem Hauptlogfile ./var/log/smarthome.log einige Meldungen raus Filtern wollte, suchte ich nach einer Möglichkeit dies zu Realisieren. Leider habe ich schon bald gemerkt, dass dies mit der aktuellen Konfiguration nicht möglich war, weswegen ich diese Änderung durchgeführt habe.
Das Resultat sieht z.B. bei mir so aus (auf das wichtigste Reduziert):
```
filters:
specialFilter:
'()': lib.logutils.Filter
name: ['knx_busmonitor', 'plugins.rtr', 'plugins.zwave', 'openzwave']
handlers:
file:
class: logging.handlers.TimedRotatingFileHandler
formatter: simple
level: INFO
filters: [specialFilter]
when: midnight
backupCount: 7
encoding: utf8
filename: ./var/log/smarthome.log
```
=> allow to build filters with a array of names

bin/smarthome.py
Currently SHNG only supports starting in foreground with DEBUG logging enabled. This will introduce a new option which will start SHNG in foreground without additional logging (just use default log settings).
This could be useful in case SHNG is started by some other program (e.g. docker, supervisor, etc.).
=> Add foreground mode to SmartHomeNG startup options

lib/config.py
When struct is used the item order is changed, because items with struct are merged at first into the central config.
These commits fix that behavior.
First commit removes uneccessary parameters which seems to be leftovers from old versions.
The second commit then fixes the behavior by merging all items into central config when struct replacement is done.
=> Keeping item order when using struct

doc/user/source/referenz/items/standard_attribute/cycle.rst, doc/user/source/referenz/items/standard_attribute/eval.rst
cycle: changed example in regard to syntax "cycle: duration = value" and added hint that None doesn't work as with eval
eval: added hint that None only works with eval, not with e.g. cycle
=> doc: updated description for items/eval and items/cycle

modules/websocket/__init__.py
When SmarthomeNG should stop it can't really stop the websocket module.
The commit "websocket: stopping asyncio thread" tries to fix stopping.
First it stores a handle to the thread (In self._server_thread was stored the return of `start()` which is still None.) to support a later join.
It avoids some possible leftover locks in case of exceptions by using "with".
It activates the commented out code to stop the event loop.
Now stopping is much faster. Sometimes an error occures when there is some work left on the loop. But that's not worse than before (for me).
The commit "websocket: using with" replaces the critical sequences
```
lock
...
do_something()
...
unlock
```
by 
```
with lock:
...
do_something()
...
```
The latter sequence is more robust against exceptions between lock and …
=> websocket: Stop behavior and cleanup

lib/model/mqttplugin.py, modules/mqtt/__init__.py
I was wondering why stopping of SmarthomeNG takes so long and still ends in a kill.
I found several vulnerable locations and a deadlock in mqtt module.
Commit 1: "mqtt: fixed locking problems; use with for locking"
This is replacing the correct pattern
```
lock
try:
...
do_something()
...
finally:
unlock
```
and the wrong pattern 
```
lock
...
do_somthing()
...
unlock
```
with "with"
```
with lock:
...
do_somthing()
...
```
Using with here has the advantage that it is easier to handle because you can't forget the unlock und even better you can't forget the "try:   finally: ",
This commit fixes therefore several parts where locking/unlocking was done without "try: finally:" which leads to left locks in case of exceptions. That means mostly the code will work, but in (rare) error cases it …
=> Mqtt: locking cleanup and deadlock fix

lib/item/items.py
Items.return_items() returns a list of path names for all items registered in shng.
As return_items() is a generator, sorting the item paths "afterwards" would comprise collecting all iterated items, building a list, sorting it and iterating again.
This patch enables getting a sorted list in the first place. The data structures in the Items class remain unchanged; only the list of item paths is returned alphabetically, which also means shorter item paths first, so the item tree is traversed from the root item down, ensuring every parent item is returned before its children.
Overhead for calling return_item() is a single if-statement checking for the (default false) boolean parameter.
=> lib.items: optionally return items sorted

lib/smarthome.py
=> lib.smarthome: change getbasedir for user function 

doc/user/source/referenz/items/funktionen.rst, doc/user/source/referenz/items/properties.rst, doc/user/source/referenz/items/standard_attribute/eval.rst, lib/item/item.py, lib/item/property.py
.. as well as prev_trigger(_by/_age) and according functions. This way it is possible to figure out what has triggered the eval expression. The property might be especially useful inside the eval expression itself but can also be used to figure out what, when (or if) an eval got triggered (without being updated, because maybe the eval didn't succeed or the value has not changed)
Example:
```
eval: value if sh..self.updated_by().startswith('admin') else None
```
only checked the update BEFORE the current update/trigger. It was not possible to figure out what has triggered the CURRENT eval expression (e.g. changing the value directly in the admin IF).
This now gives the correct result without altering any currently available property or function
```
eval: value if …
```
=> lib.item: introduce new property last_trigger(_by/_age)

doc/user/source/visualisierung/reverse_proxy.rst
If the smarthome server has an other IP adress than the ReverseProxy then the following entry lead to a not working websocket connection!
```
##
##
upstream websocket {
server 127.0.0.1:2424;
}
```
Thus the docu has to be corrected to keep more general to work also, when the IP adresses differs.
The better solution is this:
```
##
##
upstream websocket {
server <SmartHomeNG LAN IP>:2424;
}
```
=> [Docu of ReverseProxy]: Correction of docu if reverseProxy has an other IP than the smarthome server

lib/shpypi.py
Hat in meinem Setup einen Fehler geworfen, weil smarthome.py keine Rechte hat ins Stammverzeichnis zu schreiben.
=> Typo beim erstellen des Log Verzeichnisses

doc/user/source/installation/komplettanleitung/07_samba.rst
- due to connection issues with windows 10 there are two points to fix
1.  the `security = user` in globals section is missing
2. the user should be `smarthome`, because you do an login on Windows by the user `smarthome` typically. Then you are also able to change settings in smartvisu folder.
=> [Samba Configuration]: Update of Docu due to Connection Issues with Windows 10

lib/config.py, lib/item/item.py
starting without / with empty modules.yaml results in ERROR; as shng runs fine without modules, this is corrected to "WARNING"
starting without / with empty plugins.yaml results in CRITICAL; as shng "runs" fine without plugins (albeit without functionality), this is corrected to "ERROR".
Furthermore, without plugins loaded, the lib.plugins.meta object is not initialized; creating items tries to access it resulting in errors. Fixed by checking availability of meta object
=> fix startup error on empty plugins/modules config

bin/locale.yaml, doc/user/source/referenz/smarthomeng/feiertage_datum_zeit.rst, lib/shtime.py
Für ein neues Plugin wäre es hilfreich den deutschen Monatsnamen direkt zu erhalten.
Da das vielleicht auch an anderen Stellen (z.B. Logiken) hilfreich sein könnte, hab ich das mal in shtime implementiert.
=> shtime: current_monthname

lib/model/sdp/protocol.py
fix buffering and buffer handling for long replies > 4096 bytes, e.g. 'Settings.GetSettings' in kodi (~120k bytes reply)
=> sdp: fix json protocol for looooong replies

lib/network.py
Limit connection attempts if connection is closed immediately after connecting. At the moment, the limit is set to 1 try per second, and after 10 connection attempts hitting the rate limit, the connection attempts are canceled.
At the moment, this is only implemented for TcpClient(). The parameters can be set according to needs in the init call.
=> lib.network: introduce connect ratelimit

doc/user/source/referenz/items/standard_attribute/log_change.rst, lib/item/item.py
- added some more options such as time, date, now
- added possibility to implement the value of an item in the log text (e.g. for updating the message)
- added possibility to define all log_rules by an item instead of a distinct value
- some minor improvements
These updates should make (together with logging.yaml) datalog, memlog and operationlog obsolete.
=> Improve and extend log_text / log_rules for item logging

doc/user/source/referenz/logging/logging_handler.rst, lib/log.py
considering current date and time as filenames.
IMPORTANT: docu needs to be updated for the operationlog and datalog plugin
Ways to test:
```
handlers:
datetime_file1:
(): lib.log.DateTimeRotatingFileHandler
formatter: shng_detail
when: 'M'
interval: 1
backupCount: 2
filename: ./var/log/testlog.log
encoding: utf8
datetime_file2:
(): lib.log.DateTimeRotatingFileHandler
formatter: shng_detail
when: 'M'
interval: 1
backupCount: 5
filename: /{year}/test-{year:02}-{month}-{day}-{hour:02}.{minute:02}
encoding: utf8
```
=> lib.log: introduce a new rotating filehandler

modules/mqtt/__init__.py
On receiving ill-formed utf-8 messages containing illegal binary data, the mqtt module throws an exception - and stops receiving further messages.
To fix this, the unicode decode error is caught, logged and the payload is discarded.
=> mqtt: add error handling for non-decodable utf-8 messages

lib/config.py, lib/smarthome.py
Vorschlag zur Lösung für fix #594 
Vor dem Mergen des Structs ins Item-Template wird ein ggf. vorhandenes Attribut 'name' entfernt, das Item behält seinen ursprünglichen Namen.
TODO:
Aus meiner Sicht gibt es drei Wege:
a) der Name aus dem Struct überschreibt den des Items (status quo)
b) der Name des Structs wird ignoriert (PR)
c) der Name des Structs wird nur übernommen, wenn das Item keinen Namen hat.
Vor- und Nachteile:
a) + nonbreaking für alle möglichen Anwendungen
- ggf. Namensdubletten bei mehrfacher Verwendung
b) + ggf. vorhandener Item-Name wird nicht überschrieben
+ keine Namensdubletten aus struct
- ggf. breaking change (falls "feature" bisher verwendet)
c) + ggf. vergebener Item-Name wird beibehalten
- ggf. Namensdubletten bei mehrfacher Verwendung
- ggf. breaking change …
=> lib.config: remove name attribute from struct root before merging

doc/user/source/referenz/items/item_zugriff.rst, lib/item/item.py, tests/test_item.py
Ich habe als Vorschlag und zur Diskussion mal meine Idee zum Handling von dicts und lists in Items ergänzt.
Martins Implementation ist unverändert, allerdings legt das Item je nach Typ die folgenden Item-Funktionen an:
list: append, prepend, insert, pop, extend, clear, delete, remove
dict: get, delete, clear, pop, popitem, update
delete statt del, weil del als reserviertes Wort nicht nutzbar ist.
Die Funktionen lassen sich quasi 1:1 wie die originalen list-/dict-Funktionen nutzen, z.B.
```
listitem.append(val)
val = listitem.pop("2:3")
dictitem.update({'foo': 'bar'})
val = dictitem.get('baz', 'sorry')
```
Zusätzlich können allen Funktionen die Parameter `caller`, `source`, `dest` mitgegeben werden.
Intern rufen die Funktionen alle `__call__` auf, so dass alle notwendigen Item-Mechaniken …
=> lib.item: add methods for list/dict manipulation

dev/sample_module/module.yaml, dev/sample_mqttplugin/__init__.py, dev/sample_mqttplugin/plugin.yaml, dev/sample_plugin/__init__.py, dev/sample_plugin/plugin.yaml, dev/sample_smartdevice_plugin/plugin.yaml, dev/sample_smartdevice_standalone_plugin/plugin.yaml, lib/model/mqttplugin.py, lib/model/smartplugin.py
This item more or less replaces the suspend_item, but it hard-stops and re-runs the plugin instead of trying to suspend it while being active.
Modified and adjusten SmartPlugin and MqttPlugin as well as both sample plugins and their plugin.yaml files. 
Works with adjusted zigbee2mqtt Plugin; plugin wishing to implement this need to
- be restartable (though metadata restartable is not queried)
- implement code snippets in init, run, stop, parse_item, update_item (see sample plugins)
Also cleaned up SmartPlugin, commented the reason for using class members and added some type hinting.
As far as I can see, the changes should be non-breaking.
=> smartplugin: add pause_item (instead of suspend item)

lib/shpypi.py
=> lib.shpypi: calculate versions for requiremens above/below given version

lib/item/item.py
added three Item methods:
- return_ancestor(level, strict):
like return_parent, but multi-level
- find_attr(attr, default, level, strict):
find attribute <attr> in ancestors, up to or at given level
- find_attribute_value(attr_ref, current_attr, default, ignore_current_item):
like _get_attribute_value, but not limited to 4 levels (uses find_attr)
find_attribute_value could - if wanted - replace _get_attribute_value and remove the limit to 4 levels
=> lib.item.item: add ancestor item/attr methods

modules/websocket/smartvisu.py
=> module websocket: fix for smartvisu protocol

lib/db.py
fixes #806 (https://github.com/smarthomeNG/plugins/issues/806)
=> lib.db: handle numeric passwords and OrderedDict lists

doc/user/source/referenz/items/funktionen.rst, lib/item/helpers.py, lib/item/item.py, lib/item/items.py
fader can be stopped by specific callers only or by all callers (except given list). Very useful for fading KNX actors that send back their status. Additionally, faders can now be changed during fading "on the fly".
=> Fader method: introduce new features

modules/mqtt/__init__.py, modules/mqtt/module.yaml
works with paho_mqtt v1 (tested: 1.6.1) and v2 (tested: 2.1.0), discriminates between v1 and v2, configuration not needed. Should be non-breaking and backwards-compatible.
Will need adjusting for paho_mqtt v3 someday.
No problems here with both versions, would like independent testing.
fixes #632
=> module mqtt: add compatibility to paho_mqtt v2

lib/plugin.py
Inserts the "identifier" (config_name) of every plugin into sh.plugins in addition to sh, thus doing the same as already is done with items. Does not overwrite sh.plugins methods or attributes.
Also, calling `sh.plugins('foo')` would return the plugin with config name 'foo' (internally calls `return_plugin('foo')`).
implements/ closes #705
=> lib.plugin: insert plugin references into sh.plugins

doc/user/source/installation/komplettanleitung/02_smarthomeng.rst, doc/user/source/referenz/items/funktionen.rst, doc/user/source/referenz/items/standard_attribute/crontab.rst, lib/item/helpers.py, lib/item/item.py, lib/scheduler.py
try to eliminate compat parsing and fix parsing of expressions containing = for comparison and as separator
=> fix splitting of time ; value ; compat
